import CommunicationComplexity.Functions.Disjointness
import CommunicationComplexity.Deterministic.Transcript
import CommunicationComplexity.InformationTheory.Entropy
import CommunicationComplexity.InformationTheory.Pinsker
import CommunicationComplexity.PublicCoin.Minimax
import Mathlib.Probability.UniformOn

namespace CommunicationComplexity

open MeasureTheory ProbabilityTheory
open scoped BigOperators

namespace Functions.Disjointness

/-!
This file starts the randomized lower bound for disjointness at a fixed small error.

The first step is the hard distribution from the information-complexity proof: choose a special
coordinate `T`; at `T`, sample two independent bits; away from `T`, sample one of the three
disjoint bit-pairs `(0,0)`, `(1,0)`, `(0,1)`.
-/

namespace RandomizedLowerBound

variable (n : ℕ+)

noncomputable instance setFinFiniteMeasureSpace :
    FiniteMeasureSpace (Set (Fin n)) :=
  FiniteMeasureSpace.of (Set (Fin n))

/-- The three possible disjoint coordinate-pairs used away from the special coordinate. -/
inductive DisjointCoordinate
  | neither
  | leftOnly
  | rightOnly
  deriving DecidableEq, Fintype

namespace DisjointCoordinate

/-- Alice's bit in a disjoint coordinate-pair. -/
def xBit : DisjointCoordinate → Bool
  | neither => false
  | leftOnly => true
  | rightOnly => false

/-- Bob's bit in a disjoint coordinate-pair. -/
def yBit : DisjointCoordinate → Bool
  | neither => false
  | leftOnly => false
  | rightOnly => true

@[simp] theorem xBit_neither : xBit neither = false := rfl
@[simp] theorem xBit_leftOnly : xBit leftOnly = true := rfl
@[simp] theorem xBit_rightOnly : xBit rightOnly = false := rfl

@[simp] theorem yBit_neither : yBit neither = false := rfl
@[simp] theorem yBit_leftOnly : yBit leftOnly = false := rfl
@[simp] theorem yBit_rightOnly : yBit rightOnly = true := rfl

@[simp] theorem card : Fintype.card DisjointCoordinate = 3 := by
  decide

/-- A disjoint coordinate-pair never has both bits equal to `true`. -/
theorem not_xBit_and_yBit (c : DisjointCoordinate) :
    ¬(xBit c = true ∧ yBit c = true) := by
  cases c <;> simp

end DisjointCoordinate

/-- The sample space for the hard distribution. The `other` coordinate at `T` is ignored; keeping
it in the sample space makes the ambient type a simple product-like finite type. -/
structure HardSample where
  T : Fin n
  xT : Bool
  yT : Bool
  other : Fin n → DisjointCoordinate
  deriving DecidableEq, Fintype

namespace HardSample

instance : Nonempty (HardSample n) :=
  ⟨{ T := ⟨0, n.pos⟩
     xT := false
     yT := false
     other := fun _ => DisjointCoordinate.neither }⟩

instance : MeasurableSpace (HardSample n) := ⊤

/-- We use the uniform distribution on the explicit hard-distribution sample space. -/
noncomputable instance measureSpace : MeasureSpace (HardSample n) :=
  ⟨ProbabilityTheory.uniformOn Set.univ⟩

noncomputable instance isProbabilityMeasure :
    IsProbabilityMeasure (volume : Measure (HardSample n)) := by
  change IsProbabilityMeasure (ProbabilityTheory.uniformOn Set.univ)
  infer_instance

noncomputable instance finiteProbabilitySpace : FiniteProbabilitySpace (HardSample n) :=
  FiniteProbabilitySpace.of (HardSample n)

private def equivProd :
    HardSample n ≃ Fin n × Bool × Bool × (Fin n → DisjointCoordinate) where
  toFun ω := (ω.T, ω.xT, ω.yT, ω.other)
  invFun p :=
    { T := p.1
      xT := p.2.1
      yT := p.2.2.1
      other := p.2.2.2 }
  left_inv ω := by
    rcases ω with ⟨T, xT, yT, other⟩
    rfl
  right_inv p := by
    rcases p with ⟨T, xT, yT, other⟩
    rfl

@[simp] theorem card :
    Fintype.card (HardSample n) = (n : ℕ) * 4 * 3 ^ (n : ℕ) := by
  calc
    Fintype.card (HardSample n) =
        Fintype.card (Fin n × Bool × Bool × (Fin n → DisjointCoordinate)) :=
      Fintype.card_congr (equivProd n)
    _ = (n : ℕ) * 4 * 3 ^ (n : ℕ) := by
      simp [Fintype.card_prod, Fintype.card_pi]
      ring

/-- Alice's bit at coordinate `i` under a hard-distribution sample. -/
def xBit (ω : HardSample n) (i : Fin n) : Bool :=
  if i = ω.T then ω.xT else (ω.other i).xBit

/-- Bob's bit at coordinate `i` under a hard-distribution sample. -/
def yBit (ω : HardSample n) (i : Fin n) : Bool :=
  if i = ω.T then ω.yT else (ω.other i).yBit

/-- Alice's input set under a hard-distribution sample. -/
def X (ω : HardSample n) : Set (Fin n) :=
  {i | xBit n ω i = true}

/-- Bob's input set under a hard-distribution sample. -/
def Y (ω : HardSample n) : Set (Fin n) :=
  {i | yBit n ω i = true}

/-- The input pair generated by a hard-distribution sample. -/
def input (ω : HardSample n) : Set (Fin n) × Set (Fin n) :=
  (X n ω, Y n ω)

/-- The event that the special coordinate is an actual intersection. -/
def specialIntersect : Set (HardSample n) :=
  {ω | ω.xT = true ∧ ω.yT = true}

/-- The event that the two special-coordinate bits have prescribed values. -/
def specialBitsEvent (bx bY : Bool) : Set (HardSample n) :=
  {ω | ω.xT = bx ∧ ω.yT = bY}

/-- The event that both special-coordinate bits are zero. -/
def specialZeroZero : Set (HardSample n) :=
  specialBitsEvent n false false

/-- The event that the generated input pair is disjoint. -/
def disjointEvent : Set (HardSample n) :=
  {ω | Disjoint (X n ω) (Y n ω)}

instance specialIntersectDecidablePred :
    DecidablePred (fun ω : HardSample n => ω ∈ specialIntersect n) := by
  intro ω
  unfold specialIntersect
  infer_instance

noncomputable instance specialIntersectFintype :
    Fintype {ω : HardSample n // ω ∈ specialIntersect n} := by
  unfold specialIntersect
  infer_instance

noncomputable instance specialBitsEventFintype (bx bY : Bool) :
    Fintype {ω : HardSample n // ω ∈ specialBitsEvent n bx bY} := by
  unfold specialBitsEvent
  infer_instance

private def specialIntersectEquiv :
    {ω : HardSample n // ω ∈ specialIntersect n} ≃
      Fin n × (Fin n → DisjointCoordinate) where
  toFun ω := (ω.1.T, ω.1.other)
  invFun p :=
    ⟨{ T := p.1
       xT := true
       yT := true
       other := p.2 }, by simp [specialIntersect]⟩
  left_inv ω := by
    rcases ω with ⟨⟨T, xT, yT, other⟩, hω⟩
    rcases hω with ⟨hxT, hyT⟩
    cases hxT
    cases hyT
    rfl
  right_inv p := by
    rcases p with ⟨T, other⟩
    rfl

private def specialBitsEventEquiv (bx bY : Bool) :
    {ω : HardSample n // ω ∈ specialBitsEvent n bx bY} ≃
      Fin n × (Fin n → DisjointCoordinate) where
  toFun ω := (ω.1.T, ω.1.other)
  invFun p :=
    ⟨{ T := p.1
       xT := bx
       yT := bY
       other := p.2 }, by simp [specialBitsEvent]⟩
  left_inv ω := by
    rcases ω with ⟨⟨T, xT, yT, other⟩, hω⟩
    rcases hω with ⟨hxT, hyT⟩
    cases hxT
    cases hyT
    rfl
  right_inv p := by
    rcases p with ⟨T, other⟩
    rfl

@[simp] theorem card_specialIntersect :
    Fintype.card {ω : HardSample n // ω ∈ specialIntersect n} =
      (n : ℕ) * 3 ^ (n : ℕ) := by
  calc
    Fintype.card {ω : HardSample n // ω ∈ specialIntersect n} =
        Fintype.card (Fin n × (Fin n → DisjointCoordinate)) :=
      Fintype.card_congr (specialIntersectEquiv n)
    _ = (n : ℕ) * 3 ^ (n : ℕ) := by
      simp [Fintype.card_prod, Fintype.card_pi]

@[simp] theorem card_specialBitsEvent (bx bY : Bool) :
    Fintype.card {ω : HardSample n // ω ∈ specialBitsEvent n bx bY} =
      (n : ℕ) * 3 ^ (n : ℕ) := by
  calc
    Fintype.card {ω : HardSample n // ω ∈ specialBitsEvent n bx bY} =
        Fintype.card (Fin n × (Fin n → DisjointCoordinate)) :=
      Fintype.card_congr (specialBitsEventEquiv n bx bY)
    _ = (n : ℕ) * 3 ^ (n : ℕ) := by
      simp [Fintype.card_prod, Fintype.card_pi]

/-- The hard input distribution, as a probability measure on input pairs. -/
noncomputable def inputProbabilityMeasure :
    ProbabilityMeasure (Set (Fin n) × Set (Fin n)) :=
  ProbabilityMeasure.map
    (⟨(volume : Measure (HardSample n)), inferInstance⟩ :
      ProbabilityMeasure (HardSample n))
    (Measurable.of_discrete.aemeasurable (f := input n))

/-- The hard input distribution packaged as a finite probability space, for use with
distributional error. -/
noncomputable def inputDist :
    FiniteProbabilitySpace (Set (Fin n) × Set (Fin n)) :=
  FiniteProbabilitySpace.ofProbabilityMeasure
    (Set (Fin n) × Set (Fin n)) (inputProbabilityMeasure n)

@[simp] theorem mem_X (ω : HardSample n) (i : Fin n) :
    i ∈ X n ω ↔ xBit n ω i = true := Iff.rfl

@[simp] theorem mem_Y (ω : HardSample n) (i : Fin n) :
    i ∈ Y n ω ↔ yBit n ω i = true := Iff.rfl

@[simp] theorem xBit_special (ω : HardSample n) :
    xBit n ω ω.T = ω.xT := by
  simp [xBit]

@[simp] theorem yBit_special (ω : HardSample n) :
    yBit n ω ω.T = ω.yT := by
  simp [yBit]

theorem xBit_of_ne_special (ω : HardSample n) {i : Fin n} (hi : i ≠ ω.T) :
    xBit n ω i = (ω.other i).xBit := by
  simp [xBit, hi]

theorem yBit_of_ne_special (ω : HardSample n) {i : Fin n} (hi : i ≠ ω.T) :
    yBit n ω i = (ω.other i).yBit := by
  simp [yBit, hi]

/-- Away from `T`, generated coordinate-pairs are disjoint. -/
theorem not_xBit_and_yBit_of_ne_special
    (ω : HardSample n) {i : Fin n} (hi : i ≠ ω.T) :
    ¬(xBit n ω i = true ∧ yBit n ω i = true) := by
  rw [xBit_of_ne_special n ω hi, yBit_of_ne_special n ω hi]
  exact DisjointCoordinate.not_xBit_and_yBit (ω.other i)

/-- The generated sets are disjoint exactly when the two special-coordinate bits do not both
equal `true`. -/
theorem disjoint_X_Y_iff (ω : HardSample n) :
    Disjoint (X n ω) (Y n ω) ↔ ¬(ω.xT = true ∧ ω.yT = true) := by
  rw [Set.disjoint_left]
  constructor
  · intro h hbits
    exact h (a := ω.T) (by simpa [X] using hbits.1) (by simpa [Y] using hbits.2)
  · intro h i hiX hiY
    by_cases hi : i = ω.T
    · subst hi
      exact h ⟨by simpa [X] using hiX, by simpa [Y] using hiY⟩
    · exact not_xBit_and_yBit_of_ne_special n ω hi ⟨hiX, hiY⟩

/-- Under the hard distribution, the disjointness value is controlled by the two special bits. -/
theorem disjointness_input_eq (ω : HardSample n) :
    disjointness n (X n ω) (Y n ω) =
      decide (¬(ω.xT = true ∧ ω.yT = true)) := by
  simp [disjointness, disjoint_X_Y_iff]

/-- The disjoint event is the complement of the special-intersection event. -/
theorem disjointEvent_eq_compl_specialIntersect :
    disjointEvent n = (specialIntersect n)ᶜ := by
  ext ω
  simp [disjointEvent, specialIntersect, disjoint_X_Y_iff]

/-- The hard distribution creates an intersection with probability `1/4`. -/
theorem measureReal_specialIntersect :
    (volume (specialIntersect n)).toReal = (1 / 4 : ℝ) := by
  classical
  letI : DecidablePred (fun ω : HardSample n => ω ∈ specialIntersect n) :=
    fun ω => Classical.propDecidable (ω ∈ specialIntersect n)
  change ((ProbabilityTheory.uniformOn Set.univ : Measure (HardSample n))
      (specialIntersect n)).toReal = (1 / 4 : ℝ)
  rw [uniformOn_univ_measureReal_eq_card_filter]
  have hfilter :
      (Finset.univ.filter fun ω : HardSample n => ω ∈ specialIntersect n).card =
        Fintype.card {ω : HardSample n // ω ∈ specialIntersect n} := by
    simp [Fintype.card_subtype]
  have hfilter_real :
      ((Finset.univ.filter fun ω : HardSample n => ω ∈ specialIntersect n).card : ℝ) =
        (Fintype.card {ω : HardSample n // ω ∈ specialIntersect n} : ℝ) := by
    exact_mod_cast hfilter
  rw [hfilter_real, card_specialIntersect, card]
  have hn : ((n : ℕ) : ℝ) ≠ 0 := by positivity
  have hpow : ((3 ^ (n : ℕ) : ℕ) : ℝ) ≠ 0 := by positivity
  norm_num [Nat.cast_mul, Nat.cast_pow]
  field_simp [hn, hpow]

/-- Each prescribed pair of special-coordinate bits has probability `1/4`. -/
theorem measureReal_specialBitsEvent (bx bY : Bool) :
    (volume (specialBitsEvent n bx bY)).toReal = (1 / 4 : ℝ) := by
  classical
  letI : DecidablePred (fun ω : HardSample n => ω ∈ specialBitsEvent n bx bY) :=
    fun ω => Classical.propDecidable (ω ∈ specialBitsEvent n bx bY)
  change ((ProbabilityTheory.uniformOn Set.univ : Measure (HardSample n))
      (specialBitsEvent n bx bY)).toReal = (1 / 4 : ℝ)
  rw [uniformOn_univ_measureReal_eq_card_filter]
  have hfilter :
      (Finset.univ.filter fun ω : HardSample n => ω ∈ specialBitsEvent n bx bY).card =
        Fintype.card {ω : HardSample n // ω ∈ specialBitsEvent n bx bY} := by
    simp [Fintype.card_subtype]
  have hfilter_real :
      ((Finset.univ.filter fun ω : HardSample n => ω ∈ specialBitsEvent n bx bY).card : ℝ) =
        (Fintype.card {ω : HardSample n // ω ∈ specialBitsEvent n bx bY} : ℝ) := by
    exact_mod_cast hfilter
  rw [hfilter_real, card_specialBitsEvent, card]
  have hn : ((n : ℕ) : ℝ) ≠ 0 := by positivity
  have hpow : ((3 ^ (n : ℕ) : ℕ) : ℝ) ≠ 0 := by positivity
  norm_num [Nat.cast_mul, Nat.cast_pow]
  field_simp [hn, hpow]

/-- The event `(X_T, Y_T) = (0, 0)` has probability `1/4`. -/
theorem measureReal_specialZeroZero :
    (volume (specialZeroZero n)).toReal = (1 / 4 : ℝ) := by
  rw [specialZeroZero, measureReal_specialBitsEvent]

/-- If both special-coordinate bits are zero, then the generated input pair is disjoint. -/
theorem specialZeroZero_subset_disjointEvent :
    specialZeroZero n ⊆ disjointEvent n := by
  intro ω hω
  rw [specialZeroZero, specialBitsEvent] at hω
  change Disjoint (X n ω) (Y n ω)
  rw [disjoint_X_Y_iff]
  intro hbits
  rw [hω.1] at hbits
  simp at hbits

/-- The hard distribution generates disjoint inputs with probability `3/4`. -/
theorem measureReal_disjointEvent :
    (volume (disjointEvent n)).toReal = (3 / 4 : ℝ) := by
  rw [disjointEvent_eq_compl_specialIntersect]
  change ((volume : Measure (HardSample n)).real ((specialIntersect n)ᶜ)) = (3 / 4 : ℝ)
  rw [measureReal_compl MeasurableSet.of_discrete]
  rw [probReal_univ]
  rw [show (volume : Measure (HardSample n)).real (specialIntersect n) = (1 / 4 : ℝ) by
    simpa [Measure.real] using measureReal_specialIntersect n]
  norm_num

/-- The disjoint event has positive measure under the hard distribution. -/
theorem measure_disjointEvent_ne_zero :
    (volume : Measure (HardSample n)) (disjointEvent n) ≠ 0 := by
  have hreal :
      ((volume : Measure (HardSample n)) (disjointEvent n)).toReal ≠ 0 := by
    rw [measureReal_disjointEvent n]
    norm_num
  exact (ENNReal.toReal_ne_zero.mp hreal).1

/-- The hard distribution conditioned on the generated input being disjoint. -/
noncomputable def disjointCondMeasure : Measure (HardSample n) :=
  (volume : Measure (HardSample n))[|disjointEvent n]

noncomputable instance disjointCondMeasure_isProbabilityMeasure :
    IsProbabilityMeasure (disjointCondMeasure n) := by
  rw [disjointCondMeasure]
  exact ProbabilityTheory.cond_isProbabilityMeasure (measure_disjointEvent_ne_zero n)

/-- The special coordinate selected by the hard distribution. -/
def specialCoordinate (ω : HardSample n) : Fin n :=
  ω.T

/-- Alice's bit at the special coordinate. -/
def specialX (ω : HardSample n) : Bool :=
  ω.xT

/-- Bob's bit at the special coordinate. -/
def specialY (ω : HardSample n) : Bool :=
  ω.yT

/-- Alice's full input bit-vector. -/
def xVector (ω : HardSample n) : Fin n → Bool :=
  xBit n ω

/-- Bob's full input bit-vector. -/
def yVector (ω : HardSample n) : Fin n → Bool :=
  yBit n ω

/-- Alice's input bits before the special coordinate, padded by `false` elsewhere so that the
codomain does not depend on `ω.T`. -/
def xBeforeSpecial (ω : HardSample n) : Fin n → Bool :=
  fun i => if i < ω.T then xBit n ω i else false

/-- Alice's input bits except at the special coordinate, padded by `false` at `ω.T`. -/
def xExceptSpecial (ω : HardSample n) : Fin n → Bool :=
  fun i => if i = ω.T then false else xBit n ω i

/-- Bob's input bits after the special coordinate, padded by `false` elsewhere. -/
def yAfterSpecial (ω : HardSample n) : Fin n → Bool :=
  fun i => if ω.T < i then yBit n ω i else false

/-- Bob's input bits except at the special coordinate, padded by `false` at `ω.T`. -/
def yExceptSpecial (ω : HardSample n) : Fin n → Bool :=
  fun i => if i = ω.T then false else yBit n ω i

/-- The conditioning variable appearing in the first information term of the textbook proof. -/
def firstConditioning (ω : HardSample n) : Fin n × (Fin n → Bool) × (Fin n → Bool) :=
  (specialCoordinate n ω, xBeforeSpecial n ω, yExceptSpecial n ω)

/-- The conditioning variable appearing in the second information term of the textbook proof. -/
def secondConditioning (ω : HardSample n) : Fin n × (Fin n → Bool) × (Fin n → Bool) :=
  (specialCoordinate n ω, xExceptSpecial n ω, yAfterSpecial n ω)

/-- The special-coordinate bit-pair. -/
def specialPair (ω : HardSample n) : Bool × Bool :=
  (specialX n ω, specialY n ω)

instance boolPairFiniteMeasureSpace : FiniteMeasureSpace (Bool × Bool) :=
  FiniteMeasureSpace.of (Bool × Bool)

/-- The uniform law on a pair of bits. -/
noncomputable def uniformBoolPair : ProbabilityMeasure (Bool × Bool) :=
  ⟨ProbabilityTheory.uniformOn Set.univ, inferInstance⟩

/-- Each bit-pair has mass `1/4` under the uniform law on two bits. -/
theorem uniformBoolPair_singleton (b : Bool × Bool) :
    ((uniformBoolPair : ProbabilityMeasure (Bool × Bool)) : Measure (Bool × Bool)).real {b} =
      (1 / 4 : ℝ) := by
  rw [uniformBoolPair]
  change (ProbabilityTheory.uniformOn Set.univ : Measure (Bool × Bool)).real {b} = (1 / 4 : ℝ)
  rw [Measure.real, ProbabilityTheory.uniformOn_univ]
  norm_num [Fintype.card_prod]

/-- Probabilities under the hard input distribution can be computed on the explicit hard
sample space by taking preimages under `input`. -/
theorem inputDist_measureReal_eq_preimage (S : Set (Set (Fin n) × Set (Fin n))) :
    letI := inputDist n
    (volume S).toReal =
      (volume ((input n) ⁻¹' S : Set (HardSample n))).toReal := by
  change
    ((inputProbabilityMeasure n : ProbabilityMeasure (Set (Fin n) × Set (Fin n))) :
        Measure (Set (Fin n) × Set (Fin n))).real S =
      (volume ((input n) ⁻¹' S : Set (HardSample n))).toReal
  rw [inputProbabilityMeasure]
  rw [Measure.real]
  rw [ProbabilityMeasure.map_apply' _ _ MeasurableSet.of_discrete]
  rfl

/-- Distributional error under the hard input distribution can be computed on the explicit
hard sample space. -/
theorem distributionalError_inputDist_eq_sample
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) :
    p.distributionalError (inputDist n) (disjointness n) =
      (volume {ω : HardSample n |
        p.run (X n ω) (Y n ω) ≠ disjointness n (X n ω) (Y n ω)}).toReal := by
  rw [Deterministic.Protocol.distributionalError]
  rw [inputDist_measureReal_eq_preimage]
  rfl

/-- The sample-space event where a deterministic protocol errs on disjointness. -/
def protocolErrorEvent
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) : Set (HardSample n) :=
  {ω | p.run (X n ω) (Y n ω) ≠ disjointness n (X n ω) (Y n ω)}

/-- The sample-space event where a deterministic protocol outputs `true`. -/
def protocolAcceptEvent
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) : Set (HardSample n) :=
  {ω | p.run (X n ω) (Y n ω) = true}

/-- The sample-space event where a deterministic protocol outputs `false`. -/
def protocolRejectEvent
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) : Set (HardSample n) :=
  {ω | p.run (X n ω) (Y n ω) = false}

/-- Distributional error under the hard input distribution is the probability of the named
sample-space error event. -/
theorem distributionalError_inputDist_eq_protocolErrorEvent
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) :
    p.distributionalError (inputDist n) (disjointness n) =
      (volume (protocolErrorEvent n p)).toReal := by
  rw [distributionalError_inputDist_eq_sample]
  rfl

/-- On disjoint samples, an error is exactly a `false` protocol output. -/
theorem mem_protocolErrorEvent_of_mem_disjointEvent
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    {ω : HardSample n} (hω : ω ∈ disjointEvent n) :
    ω ∈ protocolErrorEvent n p ↔ ω ∈ protocolRejectEvent n p := by
  have hdisj : Disjoint (X n ω) (Y n ω) := hω
  simp [protocolErrorEvent, protocolRejectEvent, disjointness, hdisj]

/-- On intersecting-at-the-special-coordinate samples, an error is exactly a `true` protocol
output. -/
theorem mem_protocolErrorEvent_of_mem_specialIntersect
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    {ω : HardSample n} (hω : ω ∈ specialIntersect n) :
    ω ∈ protocolErrorEvent n p ↔ ω ∈ protocolAcceptEvent n p := by
  have hnot_disj : ¬Disjoint (X n ω) (Y n ω) := by
    rw [disjoint_X_Y_iff]
    exact not_not_intro hω
  simp [protocolErrorEvent, protocolAcceptEvent, disjointness, hnot_disj]

/-- The transcript random variable induced by a deterministic protocol on the hard sample space. -/
noncomputable def message
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (ω : HardSample n) : p.Leaf :=
  p.transcript (input n ω)

/-- The `Z = (M, T, X_{<T}, Y_{>T})` variable used in the Pinsker step. -/
noncomputable def zVariable
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (ω : HardSample n) :
    p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool)) :=
  (message n p ω, specialCoordinate n ω, xBeforeSpecial n ω, yAfterSpecial n ω)

/-- The hard-distribution measure conditioned on a `zVariable` fiber. -/
noncomputable def zFiberMeasure
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (z : p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool))) :
    Measure (HardSample n) :=
  (volume : Measure (HardSample n))[|zVariable n p ← z]

/-- A positive-mass `zVariable` fiber gives a probability measure. -/
theorem zFiberMeasure_isProbabilityMeasure
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (z : p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool)))
    (hz : (volume : Measure (HardSample n)) ((zVariable n p) ⁻¹' {z}) ≠ 0) :
    IsProbabilityMeasure (zFiberMeasure n p z) := by
  rw [zFiberMeasure]
  exact ProbabilityTheory.cond_isProbabilityMeasure hz

/-- Positive mass under the disjoint-conditioned measure implies positive mass under the
original hard distribution. -/
theorem volume_zFiber_ne_zero_of_disjointCondMeasure_ne_zero
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (z : p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool)))
    (hz : (disjointCondMeasure n) ((zVariable n p) ⁻¹' {z}) ≠ 0) :
    (volume : Measure (HardSample n)) ((zVariable n p) ⁻¹' {z}) ≠ 0 := by
  have hac : (disjointCondMeasure n) ≪ (volume : Measure (HardSample n)) := by
    rw [disjointCondMeasure]
    exact ProbabilityTheory.cond_absolutelyContinuous
  intro hzero
  exact hz (hac hzero)

/-- The conditional law of the special bit-pair on a positive-mass `zVariable` fiber. -/
noncomputable def conditionalSpecialPairLaw
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (z : p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool)))
    (hz : (volume : Measure (HardSample n)) ((zVariable n p) ⁻¹' {z}) ≠ 0) :
    ProbabilityMeasure (Bool × Bool) :=
  ProbabilityMeasure.map
    (⟨zFiberMeasure n p z, zFiberMeasure_isProbabilityMeasure n p z hz⟩ :
      ProbabilityMeasure (HardSample n))
    (Measurable.of_discrete.aemeasurable (f := specialPair n))

/-- A `z` value is good when the conditional law of `(X_T, Y_T)` given `z` is close to uniform. -/
def goodZ
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (γ : ℝ)
    (z : p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool))) : Prop :=
  ∀ hz : (volume : Measure (HardSample n)) ((zVariable n p) ⁻¹' {z}) ≠ 0,
    tvDistance (conditionalSpecialPairLaw n p z hz) uniformBoolPair ≤ 2 * γ

/-- The sample-space event that the sampled `zVariable` value is good. -/
def goodZEvent
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (γ : ℝ) : Set (HardSample n) :=
  {ω | goodZ n p γ (zVariable n p ω)}

/-- On a positive-mass `Z=z` fiber, the conditional `specialPair` singleton mass is the
corresponding preimage probability under the fiber measure. -/
theorem conditionalSpecialPairLaw_singleton
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (z : p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool)))
    (hz : (volume : Measure (HardSample n)) ((zVariable n p) ⁻¹' {z}) ≠ 0)
    (b : Bool × Bool) :
    ((conditionalSpecialPairLaw n p z hz : ProbabilityMeasure (Bool × Bool)) :
        Measure (Bool × Bool)).real {b} =
      (zFiberMeasure n p z).real ((specialPair n) ⁻¹' {b}) := by
  rw [conditionalSpecialPairLaw]
  rw [Measure.real]
  rw [ProbabilityMeasure.map_apply' _ _ MeasurableSet.of_discrete]
  rfl

/-- Intersecting with the defining `Z=z` fiber does not change probabilities under the
corresponding fiber measure. -/
theorem zFiberMeasure_inter_fiber
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (z : p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool)))
    (S : Set (HardSample n)) :
    (zFiberMeasure n p z).real (((zVariable n p) ⁻¹' {z}) ∩ S) =
      (zFiberMeasure n p z).real S := by
  rw [zFiberMeasure]
  rw [Measure.real]
  rw [ProbabilityTheory.cond_inter_self MeasurableSet.of_discrete]
  rfl

/-- Law of total probability over the finite `zVariable` fibers. -/
theorem measureReal_eq_sum_zFiberMeasure_real
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (S : Set (HardSample n)) :
    (volume : Measure (HardSample n)).real S =
      ∑ z : p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool)),
        (volume : Measure (HardSample n)).real ((zVariable n p) ⁻¹' {z}) *
          (zFiberMeasure n p z).real S := by
  classical
  let μ : Measure (HardSample n) := volume
  let Z := zVariable n p
  have htotal := ProbabilityTheory.sum_meas_smul_cond_fiber (X := Z) Measurable.of_discrete μ
  have hS : (∑ z, μ (Z ⁻¹' {z}) • μ[|Z ← z]) S = μ S := by
    rw [htotal]
  change μ.real S =
      ∑ z : p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool)),
        μ.real (Z ⁻¹' {z}) * (μ[|Z ← z]).real S
  rw [Measure.real]
  rw [← hS]
  simp only [Measure.real, Measure.coe_finset_sum, Finset.sum_apply, Measure.coe_smul,
    Pi.smul_apply, smul_eq_mul]
  rw [ENNReal.toReal_sum]
  · apply Finset.sum_congr rfl
    intro z _
    rw [ENNReal.toReal_mul]
  · intro z _
    exact ENNReal.mul_ne_top (measure_ne_top _ _) (measure_ne_top _ _)

/-- Protocol error probability decomposed over the finite `zVariable` fibers. -/
theorem protocolErrorEvent_measureReal_eq_sum_zFiberMeasure_real
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) :
    (volume : Measure (HardSample n)).real (protocolErrorEvent n p) =
      ∑ z : p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool)),
        (volume : Measure (HardSample n)).real ((zVariable n p) ⁻¹' {z}) *
          (zFiberMeasure n p z).real (protocolErrorEvent n p) :=
  measureReal_eq_sum_zFiberMeasure_real n p (protocolErrorEvent n p)

/-- A good `z` gives the expected singleton-mass estimate for the conditional special-pair law. -/
theorem abs_conditionalSpecialPairLaw_singleton_sub_quarter_le
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    {γ : ℝ}
    {z : p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool))}
    (hgood : goodZ n p γ z)
    (hz : (volume : Measure (HardSample n)) ((zVariable n p) ⁻¹' {z}) ≠ 0)
    (b : Bool × Bool) :
    |((conditionalSpecialPairLaw n p z hz : ProbabilityMeasure (Bool × Bool)) :
        Measure (Bool × Bool)).real {b} - (1 / 4 : ℝ)| ≤ 2 * γ := by
  have htv :=
    TVDistance.abs_measureReal_sub_le_tvDistance
      (conditionalSpecialPairLaw n p z hz) uniformBoolPair
      ⟨({b} : Set (Bool × Bool)), MeasurableSet.of_discrete⟩
  rw [uniformBoolPair_singleton] at htv
  exact htv.trans (hgood hz)

/-- A good `z` gives a lower bound on each singleton mass of the conditional special-pair law. -/
theorem quarter_sub_two_mul_le_conditionalSpecialPairLaw_singleton
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    {γ : ℝ}
    {z : p.Leaf × (Fin n × (Fin n → Bool) × (Fin n → Bool))}
    (hgood : goodZ n p γ z)
    (hz : (volume : Measure (HardSample n)) ((zVariable n p) ⁻¹' {z}) ≠ 0)
    (b : Bool × Bool) :
    (1 / 4 : ℝ) - 2 * γ ≤
      ((conditionalSpecialPairLaw n p z hz : ProbabilityMeasure (Bool × Bool)) :
        Measure (Bool × Bool)).real {b} := by
  have h :=
    abs_conditionalSpecialPairLaw_singleton_sub_quarter_le n p hgood hz b
  rw [abs_le] at h
  linarith

/-- On a good `Z` fiber, the conditional protocol-error probability is at least
`1 / 4 - 2 * γ`. If the protocol output on the fiber is `true`, then the `(true, true)` special
bit-pair witnesses errors; otherwise `(false, false)` witnesses errors. -/
theorem quarter_sub_two_mul_le_zFiberMeasure_protocolErrorEvent
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    {γ : ℝ} {ω : HardSample n}
    (hgood : goodZ n p γ (zVariable n p ω))
    (hz : (volume : Measure (HardSample n)) ((zVariable n p) ⁻¹' {zVariable n p ω}) ≠ 0) :
    (1 / 4 : ℝ) - 2 * γ ≤
      (zFiberMeasure n p (zVariable n p ω)).real (protocolErrorEvent n p) := by
  haveI : IsFiniteMeasure (zFiberMeasure n p (zVariable n p ω)) := by
    rw [zFiberMeasure]
    infer_instance
  by_cases hrun : p.run (X n ω) (Y n ω) = true
  · have hmass :=
      quarter_sub_two_mul_le_conditionalSpecialPairLaw_singleton n p hgood hz (true, true)
    have hsubset :
        ((zVariable n p) ⁻¹' {zVariable n p ω}) ∩
            ((specialPair n) ⁻¹' {((true, true) : Bool × Bool)}) ⊆
          protocolErrorEvent n p := by
      intro ω' hω'
      have hzEq : zVariable n p ω' = zVariable n p ω := by
        simpa using hω'.1
      have hrun' : p.run (X n ω') (Y n ω') = true := by
        have hrunEq :=
          Deterministic.Protocol.run_eq_of_transcript_eq p (congrArg Prod.fst hzEq)
        simpa [input] using hrunEq.trans hrun
      have hbits : ω'.xT = true ∧ ω'.yT = true := by
        have hpair : specialPair n ω' = (true, true) := by
          simpa using hω'.2
        simpa [specialPair, specialX, specialY] using hpair
      have hnot_disj : ¬Disjoint (X n ω') (Y n ω') := by
        rw [disjoint_X_Y_iff]
        exact not_not_intro hbits
      simp [protocolErrorEvent, disjointness, hrun', hnot_disj]
    have hmono :
        (zFiberMeasure n p (zVariable n p ω)).real
            (((zVariable n p) ⁻¹' {zVariable n p ω}) ∩
              ((specialPair n) ⁻¹' {((true, true) : Bool × Bool)})) ≤
          (zFiberMeasure n p (zVariable n p ω)).real (protocolErrorEvent n p) :=
      measureReal_mono hsubset (measure_ne_top _ _)
    rw [zFiberMeasure_inter_fiber] at hmono
    rw [← conditionalSpecialPairLaw_singleton n p (zVariable n p ω) hz (true, true)] at hmono
    exact hmass.trans hmono
  · have hrun_false : p.run (X n ω) (Y n ω) = false := by
      cases h : p.run (X n ω) (Y n ω) <;> simp_all
    have hmass :=
      quarter_sub_two_mul_le_conditionalSpecialPairLaw_singleton n p hgood hz (false, false)
    have hsubset :
        ((zVariable n p) ⁻¹' {zVariable n p ω}) ∩
            ((specialPair n) ⁻¹' {((false, false) : Bool × Bool)}) ⊆
          protocolErrorEvent n p := by
      intro ω' hω'
      have hzEq : zVariable n p ω' = zVariable n p ω := by
        simpa using hω'.1
      have hrun' : p.run (X n ω') (Y n ω') = false := by
        have hrunEq :=
          Deterministic.Protocol.run_eq_of_transcript_eq p (congrArg Prod.fst hzEq)
        simpa [input] using hrunEq.trans hrun_false
      have hbits : ω'.xT = false ∧ ω'.yT = false := by
        have hpair : specialPair n ω' = (false, false) := by
          simpa using hω'.2
        simpa [specialPair, specialX, specialY] using hpair
      have hdisj : Disjoint (X n ω') (Y n ω') := by
        rw [disjoint_X_Y_iff]
        intro hboth
        rw [hbits.1] at hboth
        simp at hboth
      simp [protocolErrorEvent, disjointness, hrun', hdisj]
    have hmono :
        (zFiberMeasure n p (zVariable n p ω)).real
            (((zVariable n p) ⁻¹' {zVariable n p ω}) ∩
              ((specialPair n) ⁻¹' {((false, false) : Bool × Bool)})) ≤
          (zFiberMeasure n p (zVariable n p ω)).real (protocolErrorEvent n p) :=
      measureReal_mono hsubset (measure_ne_top _ _)
    rw [zFiberMeasure_inter_fiber] at hmono
    rw [← conditionalSpecialPairLaw_singleton n p (zVariable n p ω) hz (false, false)] at hmono
    exact hmass.trans hmono

/-- Variant of the good-fiber error lower bound where positivity is known only after
conditioning on the disjoint event. -/
theorem quarter_sub_two_mul_le_zFiberMeasure_protocolErrorEvent_of_disjointCondMeasure
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    {γ : ℝ} {ω : HardSample n}
    (hgood : goodZ n p γ (zVariable n p ω))
    (hz : (disjointCondMeasure n) ((zVariable n p) ⁻¹' {zVariable n p ω}) ≠ 0) :
    (1 / 4 : ℝ) - 2 * γ ≤
      (zFiberMeasure n p (zVariable n p ω)).real (protocolErrorEvent n p) :=
  quarter_sub_two_mul_le_zFiberMeasure_protocolErrorEvent n p hgood
    (volume_zFiber_ne_zero_of_disjointCondMeasure_ne_zero n p (zVariable n p ω) hz)

/-- Event-form version of the good-fiber error lower bound. -/
theorem quarter_sub_two_mul_le_zFiberMeasure_protocolErrorEvent_of_mem_goodZEvent
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    {γ : ℝ} {ω : HardSample n}
    (hgood : ω ∈ goodZEvent n p γ)
    (hz : (disjointCondMeasure n) ((zVariable n p) ⁻¹' {zVariable n p ω}) ≠ 0) :
    (1 / 4 : ℝ) - 2 * γ ≤
      (zFiberMeasure n p (zVariable n p ω)).real (protocolErrorEvent n p) :=
  quarter_sub_two_mul_le_zFiberMeasure_protocolErrorEvent_of_disjointCondMeasure n p hgood hz

/-- The transcript entropy is at most the protocol length in bits, for any ambient measure. -/
theorem entropy_message_le_complexity_mul_log_two_of_measure
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (μ : Measure (HardSample n)) :
    H[message n p ; μ] ≤
      p.complexity * Real.log 2 := by
  letI : Nonempty p.Leaf := ⟨p.transcript (∅, ∅)⟩
  exact ProbabilityTheory.entropy_le_nat_mul_log_two_of_card_le_two_pow
    (message n p) μ
    (Deterministic.Protocol.card_leaf_le_two_pow_complexity p)

/-- The transcript entropy under the hard distribution is at most the protocol length in bits. -/
theorem entropy_message_le_complexity_mul_log_two
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) :
    H[message n p ; (volume : Measure (HardSample n))] ≤
      p.complexity * Real.log 2 :=
  entropy_message_le_complexity_mul_log_two_of_measure n p (volume : Measure (HardSample n))

/-- The first information term in the special-coordinate information lower bound. -/
noncomputable def firstInfoTerm
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) : ℝ :=
  I[specialX n : message n p | firstConditioning n ; disjointCondMeasure n]

/-- The second information term in the special-coordinate information lower bound. -/
noncomputable def secondInfoTerm
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) : ℝ :=
  I[specialY n : message n p | secondConditioning n ; disjointCondMeasure n]

/-- The total information revealed about the special coordinate under the disjoint conditioning. -/
noncomputable def specialInfo
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) : ℝ :=
  firstInfoTerm n p + secondInfoTerm n p

/-- The first special-coordinate information term is bounded by the transcript length. -/
theorem firstInfoTerm_le_complexity_mul_log_two
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) :
    firstInfoTerm n p ≤ p.complexity * Real.log 2 := by
  rw [firstInfoTerm]
  exact (ProbabilityTheory.condMutualInfo_le_entropy_right
    (μ := disjointCondMeasure n)
    (X := specialX n) (Y := message n p) (Z := firstConditioning n)
    Measurable.of_discrete Measurable.of_discrete Measurable.of_discrete).trans
    (entropy_message_le_complexity_mul_log_two_of_measure n p (disjointCondMeasure n))

/-- The first special-coordinate information term is nonnegative. -/
theorem firstInfoTerm_nonneg
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) :
    0 ≤ firstInfoTerm n p := by
  rw [firstInfoTerm]
  exact ProbabilityTheory.condMutualInfo_nonneg
    (μ := disjointCondMeasure n)
    (X := specialX n) (Y := message n p) (Z := firstConditioning n)
    Measurable.of_discrete Measurable.of_discrete

/-- The second special-coordinate information term is bounded by the transcript length. -/
theorem secondInfoTerm_le_complexity_mul_log_two
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) :
    secondInfoTerm n p ≤ p.complexity * Real.log 2 := by
  rw [secondInfoTerm]
  exact (ProbabilityTheory.condMutualInfo_le_entropy_right
    (μ := disjointCondMeasure n)
    (X := specialY n) (Y := message n p) (Z := secondConditioning n)
    Measurable.of_discrete Measurable.of_discrete Measurable.of_discrete).trans
    (entropy_message_le_complexity_mul_log_two_of_measure n p (disjointCondMeasure n))

/-- The second special-coordinate information term is nonnegative. -/
theorem secondInfoTerm_nonneg
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) :
    0 ≤ secondInfoTerm n p := by
  rw [secondInfoTerm]
  exact ProbabilityTheory.condMutualInfo_nonneg
    (μ := disjointCondMeasure n)
    (X := specialY n) (Y := message n p) (Z := secondConditioning n)
    Measurable.of_discrete Measurable.of_discrete

/-- The total special-coordinate information is at most twice the transcript length in bits. -/
theorem specialInfo_le_two_mul_complexity_mul_log_two
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) :
    specialInfo n p ≤ 2 * (p.complexity * Real.log 2) := by
  rw [specialInfo]
  linarith [firstInfoTerm_le_complexity_mul_log_two n p,
    secondInfoTerm_le_complexity_mul_log_two n p]

/-- The total special-coordinate information is nonnegative. -/
theorem specialInfo_nonneg
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) :
    0 ≤ specialInfo n p := by
  rw [specialInfo]
  linarith [firstInfoTerm_nonneg n p, secondInfoTerm_nonneg n p]

/-- The generated input belongs to the transcript leaf of any deterministic protocol. -/
theorem input_mem_transcript
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) (ω : HardSample n) :
    input n ω ∈
      (message n p ω : Set (Set (Fin n) × Set (Fin n))) :=
  Deterministic.Protocol.mem_transcript p (input n ω)

/-- The generated pair belongs to the transcript leaf of any deterministic protocol. -/
theorem generated_pair_mem_transcript
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool) (ω : HardSample n) :
    (X n ω, Y n ω) ∈
      (message n p ω : Set (Set (Fin n) × Set (Fin n))) :=
  input_mem_transcript n p ω

/-- If a generated input belongs to the transcript leaf of another generated input, then the
protocol has the same output on those two generated inputs. -/
theorem run_eq_of_mem_message
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    (ω ω' : HardSample n)
    (hω' : input n ω' ∈ (message n p ω : Set (Set (Fin n) × Set (Fin n)))) :
    p.run (X n ω) (Y n ω) = p.run (X n ω') (Y n ω') := by
  exact Deterministic.Protocol.run_eq_of_mem_transcript p (input n ω) (input n ω') hω'

/-- Equal transcript messages force equal protocol outputs on generated inputs. -/
theorem run_eq_of_message_eq
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    {ω ω' : HardSample n}
    (h : message n p ω = message n p ω') :
    p.run (X n ω) (Y n ω) = p.run (X n ω') (Y n ω') := by
  exact Deterministic.Protocol.run_eq_of_transcript_eq p h

/-- Equal `Z` values have equal transcript messages, hence equal protocol outputs. -/
theorem run_eq_of_zVariable_eq
    (p : Deterministic.Protocol (Set (Fin n)) (Set (Fin n)) Bool)
    {ω ω' : HardSample n}
    (h : zVariable n p ω = zVariable n p ω') :
    p.run (X n ω) (Y n ω) = p.run (X n ω') (Y n ω') := by
  exact run_eq_of_message_eq n p (congrArg Prod.fst h)

end HardSample

end RandomizedLowerBound

end Functions.Disjointness

end CommunicationComplexity
