name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # Build docs on merges to main
  workflow_dispatch:

concurrency:
  group: github-pages
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    # if: github.repository == 'Communication-Complexity-Group-Project/communication-complexity-lean'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and lint the project
        id: build-lean
        uses: leanprover/lean-action@v1
        with:
          build-args: "--wfail --iofail"

      - name: Build project documentation
        id: build-docgen
        uses: leanprover-community/docgen-action@main
        with:
          build-page: true
          deploy: true

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docbuild/.lake/build/doc

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
